hello-remote:
  wasm-file: ./hello.wasm
  wasm-url: http://localhost:9090/registry/pull/hello.wasm
  wasm-url-auth-header: admin-registry-token=morrison-hotel
  wasm-function: handle
  http-port: 8080
  log-level: info

hello-local:
  wasm-file: ./hello.wasm
  wasm-function: handle
  http-port: 8080
  log-level: info