---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: task-pv-wasm-registry-volume
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 10Mi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/wasm-registry-files"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: task-pv-wasm-registry-claim
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Mi
---
# Create a pod to copy manualy files to the PersistentVolume
apiVersion: v1
kind: Pod
metadata:
  name: wasm-registry-store
spec:
  volumes:
    - name: wasm-registry-storage
      persistentVolumeClaim:
        claimName: task-pv-wasm-registry-claim
  containers:
    - name: wasm-registry-container
      image: busybox:latest
      imagePullPolicy: IfNotPresent
      command:
        - sleep
        - "3600"
      volumeMounts:
        - mountPath: /wasm-registry-files
          name: wasm-registry-storage

