---
# The configuration file specifies that the volume is at /mnt/data on the cluster's Node.
# The configuration also specifies a size of 10 gibibytes and an access mode of ReadWriteOnce, 
# which means the volume can be mounted as read-write by a single Node. 
# It defines the StorageClass name manual for the PersistentVolume,
# which will be used to bind PersistentVolumeClaim requests to this PersistentVolume.
# Ref: https://kubernetes.io/docs/tasks/configure-pod-container/configure-persistent-volume-storage/

apiVersion: v1
kind: PersistentVolume
metadata:
  name: task-pv-volume
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 10Mi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/data"
---
# The next step is to create a PersistentVolumeClaim. 
# Pods use PersistentVolumeClaims to request physical storage. 
# In this exercise, you create a PersistentVolumeClaim that requests a volume 
#of at least three gibibytes that can provide read-write access for at most one Node at a time.
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: task-pv-claim
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Mi
---
# Create a pod to copy manualy files to the PersistentVolume
apiVersion: v1
kind: Pod
metadata:
  name: task-pv-pod
spec:
  volumes:
    - name: task-pv-storage
      persistentVolumeClaim:
        claimName: task-pv-claim
  containers:
    - name: task-pv-container
      #image: debian:latest
      image: busybox:latest
      imagePullPolicy: IfNotPresent
      command:
        - sleep
        - "3600"
      volumeMounts:
        - mountPath: /data
          name: task-pv-storage

