hello-plugin:
  wasm-file: ../hello-plugin/hello.wasm
  wasm-function: say_hello
  http-port: 8085
  log-level: info
  #allow-hosts: '["localhost", "127.0.0.1"]'
  #allow-paths: '{"path":"/"}'
  #config: '{"name":"hello"}'

simple-plugin:
  wasm-file: ../simple-plugin/simple.wasm
  wasm-function: say_hello
  http-port: 8086

simple-rust-plugin:
  wasm-file: ../../rustlang/simple-plugin/target/wasm32-wasi/release/simple_plugin.wasm
  wasm-function: hello
  http-port: 8087

hello-rust-plugin:
  wasm-file: ../../rustlang/hello-plugin/target/wasm32-wasi/release/hello_plugin.wasm
  wasm-function: hello
  http-port: 8088

hello-rust-plugin-2:
  wasm-file: ../../rustlang/hello-plugin/target/wasm32-wasi/release/hello_plugin.wasm
  wasm-function: hello
  http-port: 8089

hello-rust-plugin-3:
  wasm-file: ../../rustlang/hello-plugin/target/wasm32-wasi/release/hello_plugin.wasm
  wasm-function: hello
  http-port: 8090

# This is 🚧 work in progress
service-discovery:
  http-port: 8888
