hello-plugin:
  wasm-file: ../hello-plugin/hello.wasm
  wasm-function: say_hello
  http-port: 8081
  log-level: info
  #allow-hosts: '["localhost", "127.0.0.1"]'
  #allow-paths: '{"path":"/"}'
  #config: '{"name":"hello"}'

simple-plugin:
  wasm-file: ../simple-plugin/simple.wasm
  wasm-function: say_hello
  http-port: 8082

simple-rust-plugin:
  wasm-file: ../../rustlang/simple-plugin/target/wasm32-wasi/release/simple_plugin.wasm
  wasm-function: hello
  http-port: 8083

hello-rust-plugin:
  wasm-file: ../../rustlang/hello-plugin/target/wasm32-wasi/release/hello_plugin.wasm
  wasm-function: hello
  http-port: 8084


# This is 🚧 work in progress
admin:
  http-port: 8888
